language: go

install:
  - go get github.com/tools/godep
  - go get google.golang.org/api/google-api-go-generator
  - godep go install ./...

script:
  - godep go test ./...

go:
  - 1.2
  - 1.3
  - 1.4
